name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64
            
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Build Electron
      run: npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          dist/*.exe
          dist/*.dmg
          dist/*.zip
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
        retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: ./artifacts
        
    - name: Display structure
      run: ls -la ./artifacts/
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/**/*
        generate_release_notes: true
        name: Genome Explorer ${{ github.ref_name }}
        body: |
          ## 🚀 Genome Explorer Desktop Application
          
          ### Download for your platform:
          
          **Windows:**
          - `*.exe` files - Choose Setup (installer) or Portable version
          
          **macOS:**
          - `*.dmg` - Disk image (recommended)
          - `*.zip` - Archive version
          
          **Linux:**
          - `*.AppImage` - Portable application (recommended)
          - `*.deb` - Debian/Ubuntu package
          
          ### Features:
          - 📊 Real-time trading charts
          - 📈 Technical indicators (RSI, SMA, EMA, MACD)
          - ⌨️ Command palette (Ctrl+P for symbols, Ctrl+I for indicators)
          - 💾 Data persistence with IndexedDB
          - 🎨 Modern dark theme with glassmorphism effects
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}