name: Build & Release (per-commit)

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
          - os: macos-13
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Compute SHORT_SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron (no publish)
        run: npm run dist -- --publish=never
        env:
          SHORT_SHA: ${{ env.SHORT_SHA }}

      - name: Rename artifacts with commit hash
        shell: bash
        run: |
          shopt -s nullglob
          for f in dist/*.{exe,dmg,zip,AppImage,deb,rpm}; do
            [ -e "$f" ] || continue
            ext="${f##*.}"
            base="$(basename "$f" ."$ext")"
            mv "$f" "dist/${base}-${SHORT_SHA}.${ext}"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ env.SHORT_SHA }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
          retention-days: 3

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./artifacts

      - name: Show files
        run: ls -la ./artifacts || true

      - name: Create GitHub Release (per commit)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: "Genome Explorer – ${{ github.sha }}"
          body: |
            Build automático da branch main.
            Commit: ${{ github.sha }}
          files: ./artifacts/**/*
          generate_release_notes: false
